[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://js.stripe.com https://www.googletagmanager.com https://www.google-analytics.com https://vitals.vercel-insights.com https://*.sentry.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.stripe.com https://www.google-analytics.com https://vitals.vercel-insights.com https://api.vapi.ai https://*.sentry.io https://o729505.ingest.sentry.io; frame-src 'self' https://js.stripe.com; media-src 'self' data: blob:;"

