import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/libs/next-auth';

export async function GET(_req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // For now, let's provide some common available area codes
    // In the future, we could make an actual API call to Vapi to get real-time availability
    const suggestedAreaCodes = [
      { code: '201', location: 'New Jersey', available: true },
      { code: '202', location: 'Washington DC', available: true },
      { code: '203', location: 'Connecticut', available: true },
      { code: '205', location: 'Alabama', available: true },
      { code: '206', location: 'Washington', available: true },
      { code: '207', location: 'Maine', available: true },
      { code: '208', location: 'Idaho', available: true },
      { code: '209', location: 'California', available: true },
      { code: '210', location: 'Texas', available: true },
      { code: '212', location: 'New York', available: true },
      { code: '213', location: 'California', available: true },
      { code: '214', location: 'Texas', available: true },
      { code: '215', location: 'Pennsylvania', available: true },
      { code: '216', location: 'Ohio', available: true },
      { code: '217', location: 'Illinois', available: true },
      { code: '218', location: 'Minnesota', available: true },
      { code: '219', location: 'Indiana', available: true },
      { code: '220', location: 'Ohio', available: true },
      { code: '224', location: 'Illinois', available: true },
      { code: '225', location: 'Louisiana', available: true },
      { code: '226', location: 'Ontario', available: true },
      { code: '228', location: 'Mississippi', available: true },
      { code: '229', location: 'Georgia', available: true },
      { code: '231', location: 'Michigan', available: true },
      { code: '234', location: 'Ohio', available: true },
      { code: '239', location: 'Florida', available: true },
      { code: '240', location: 'Maryland', available: true },
      { code: '248', location: 'Michigan', available: true },
      { code: '251', location: 'Alabama', available: true },
      { code: '252', location: 'North Carolina', available: true },
      { code: '253', location: 'Washington', available: true },
      { code: '254', location: 'Texas', available: true },
      { code: '256', location: 'Alabama', available: true },
      { code: '260', location: 'Indiana', available: true },
      { code: '262', location: 'Wisconsin', available: true },
      { code: '267', location: 'Pennsylvania', available: true },
      { code: '269', location: 'Michigan', available: true },
      { code: '270', location: 'Kentucky', available: true },
      { code: '272', location: 'Pennsylvania', available: true },
      { code: '274', location: 'Wisconsin', available: true },
      { code: '276', location: 'Virginia', available: true },
      { code: '281', location: 'Texas', available: true },
      { code: '283', location: 'Ohio', available: true },
      { code: '301', location: 'Maryland', available: true },
      { code: '302', location: 'Delaware', available: true },
      { code: '303', location: 'Colorado', available: true },
      { code: '304', location: 'West Virginia', available: true },
      { code: '305', location: 'Florida', available: true },
      { code: '307', location: 'Wyoming', available: true },
      { code: '308', location: 'Nebraska', available: true },
      { code: '309', location: 'Illinois', available: true },
      { code: '310', location: 'California', available: true },
      { code: '312', location: 'Illinois', available: true },
      { code: '313', location: 'Michigan', available: true },
      { code: '314', location: 'Missouri', available: true },
      { code: '315', location: 'New York', available: true },
      { code: '316', location: 'Kansas', available: true },
      { code: '317', location: 'Indiana', available: true },
      { code: '318', location: 'Louisiana', available: true },
      { code: '319', location: 'Iowa', available: true },
      { code: '320', location: 'Minnesota', available: true },
      { code: '321', location: 'Florida', available: true },
      { code: '323', location: 'California', available: true },
      { code: '325', location: 'Texas', available: true },
      { code: '330', location: 'Ohio', available: true },
      { code: '331', location: 'Illinois', available: true },
      { code: '334', location: 'Alabama', available: true },
      { code: '336', location: 'North Carolina', available: true },
      { code: '337', location: 'Louisiana', available: true },
      { code: '339', location: 'Massachusetts', available: true },
      { code: '341', location: 'California', available: true },
      { code: '346', location: 'Texas', available: true },
      { code: '347', location: 'New York', available: true },
      { code: '351', location: 'Massachusetts', available: true },
      { code: '352', location: 'Florida', available: true },
      { code: '360', location: 'Washington', available: true },
      { code: '361', location: 'Texas', available: true },
      { code: '364', location: 'Kentucky', available: true },
      { code: '365', location: 'Ontario', available: true },
      { code: '380', location: 'Ohio', available: true },
      { code: '385', location: 'Utah', available: true },
      { code: '386', location: 'Florida', available: true },
      { code: '401', location: 'Rhode Island', available: true },
      { code: '402', location: 'Nebraska', available: true },
      { code: '404', location: 'Georgia', available: true },
      { code: '405', location: 'Oklahoma', available: true },
      { code: '406', location: 'Montana', available: true },
      { code: '407', location: 'Florida', available: true },
      { code: '408', location: 'California', available: true },
      { code: '409', location: 'Texas', available: true },
      { code: '410', location: 'Maryland', available: true },
      { code: '412', location: 'Pennsylvania', available: true },
      { code: '413', location: 'Massachusetts', available: true },
      { code: '414', location: 'Wisconsin', available: true },
      { code: '415', location: 'California', available: true },
      { code: '417', location: 'Missouri', available: true },
      { code: '419', location: 'Ohio', available: true },
      { code: '423', location: 'Tennessee', available: true },
      { code: '424', location: 'California', available: true },
      { code: '425', location: 'Washington', available: true },
      { code: '430', location: 'Texas', available: true },
      { code: '432', location: 'Texas', available: true },
      { code: '434', location: 'Virginia', available: true },
      { code: '435', location: 'Utah', available: true },
      { code: '440', location: 'Ohio', available: true },
      { code: '442', location: 'California', available: true },
      { code: '443', location: 'Maryland', available: true },
      { code: '445', location: 'Pennsylvania', available: true },
      { code: '447', location: 'Illinois', available: true },
      { code: '458', location: 'Oregon', available: true },
      { code: '463', location: 'Indiana', available: true },
      { code: '464', location: 'Illinois', available: true },
      { code: '469', location: 'Texas', available: true },
      { code: '470', location: 'Georgia', available: true },
      { code: '475', location: 'Connecticut', available: true },
      { code: '478', location: 'Georgia', available: true },
      { code: '479', location: 'Arkansas', available: true },
      { code: '480', location: 'Arizona', available: true },
      { code: '484', location: 'Pennsylvania', available: true },
      { code: '501', location: 'Arkansas', available: true },
      { code: '502', location: 'Kentucky', available: true },
      { code: '503', location: 'Oregon', available: true },
      { code: '504', location: 'Louisiana', available: true },
      { code: '505', location: 'New Mexico', available: true },
      { code: '507', location: 'Minnesota', available: true },
      { code: '508', location: 'Massachusetts', available: true },
      { code: '509', location: 'Washington', available: true },
      { code: '510', location: 'California', available: true },
      { code: '512', location: 'Texas', available: true },
      { code: '513', location: 'Ohio', available: true },
      { code: '515', location: 'Iowa', available: true },
      { code: '516', location: 'New York', available: true },
      { code: '517', location: 'Michigan', available: true },
      { code: '518', location: 'New York', available: true },
      { code: '520', location: 'Arizona', available: true },
      { code: '530', location: 'California', available: true },
      { code: '531', location: 'Nebraska', available: true },
      { code: '534', location: 'Wisconsin', available: true },
      { code: '539', location: 'Oklahoma', available: true },
      { code: '540', location: 'Virginia', available: true },
      { code: '541', location: 'Oregon', available: true },
      { code: '551', location: 'New Jersey', available: true },
      { code: '559', location: 'California', available: true },
      { code: '561', location: 'Florida', available: true },
      { code: '562', location: 'California', available: true },
      { code: '563', location: 'Iowa', available: true },
      { code: '564', location: 'Washington', available: true },
      { code: '567', location: 'Ohio', available: true },
      { code: '570', location: 'Pennsylvania', available: true },
      { code: '571', location: 'Virginia', available: true },
      { code: '573', location: 'Missouri', available: true },
      { code: '574', location: 'Indiana', available: true },
      { code: '575', location: 'New Mexico', available: true },
      { code: '580', location: 'Oklahoma', available: true },
      { code: '585', location: 'New York', available: true },
      { code: '586', location: 'Michigan', available: true },
      { code: '601', location: 'Mississippi', available: true },
      { code: '602', location: 'Arizona', available: true },
      { code: '603', location: 'New Hampshire', available: true },
      { code: '605', location: 'South Dakota', available: true },
      { code: '606', location: 'Kentucky', available: true },
      { code: '607', location: 'New York', available: true },
      { code: '608', location: 'Wisconsin', available: true },
      { code: '609', location: 'New Jersey', available: true },
      { code: '610', location: 'Pennsylvania', available: true },
      { code: '612', location: 'Minnesota', available: true },
      { code: '614', location: 'Ohio', available: true },
      { code: '615', location: 'Tennessee', available: true },
      { code: '616', location: 'Michigan', available: true },
      { code: '617', location: 'Massachusetts', available: true },
      { code: '618', location: 'Illinois', available: true },
      { code: '619', location: 'California', available: true },
      { code: '620', location: 'Kansas', available: true },
      { code: '623', location: 'Arizona', available: true },
      { code: '626', location: 'California', available: true },
      { code: '628', location: 'California', available: true },
      { code: '629', location: 'Tennessee', available: true },
      { code: '630', location: 'Illinois', available: true },
      { code: '631', location: 'New York', available: true },
      { code: '636', location: 'Missouri', available: true },
      { code: '641', location: 'Iowa', available: true },
      { code: '646', location: 'New York', available: true },
      { code: '650', location: 'California', available: true },
      { code: '651', location: 'Minnesota', available: true },
      { code: '657', location: 'California', available: true },
      { code: '660', location: 'Missouri', available: true },
      { code: '661', location: 'California', available: true },
      { code: '662', location: 'Mississippi', available: true },
      { code: '667', location: 'Maryland', available: true },
      { code: '669', location: 'California', available: true },
      { code: '678', location: 'Georgia', available: true },
      { code: '681', location: 'West Virginia', available: true },
      { code: '682', location: 'Texas', available: true },
      { code: '689', location: 'Florida', available: true },
      { code: '701', location: 'North Dakota', available: true },
      { code: '702', location: 'Nevada', available: true },
      { code: '703', location: 'Virginia', available: true },
      { code: '704', location: 'North Carolina', available: true },
      { code: '706', location: 'Georgia', available: true },
      { code: '707', location: 'California', available: true },
      { code: '708', location: 'Illinois', available: true },
      { code: '712', location: 'Iowa', available: true },
      { code: '713', location: 'Texas', available: true },
      { code: '714', location: 'California', available: true },
      { code: '715', location: 'Wisconsin', available: true },
      { code: '716', location: 'New York', available: true },
      { code: '717', location: 'Pennsylvania', available: true },
      { code: '718', location: 'New York', available: true },
      { code: '719', location: 'Colorado', available: true },
      { code: '720', location: 'Colorado', available: true },
      { code: '724', location: 'Pennsylvania', available: true },
      { code: '725', location: 'Nevada', available: true },
      { code: '727', location: 'Florida', available: true },
      { code: '731', location: 'Tennessee', available: true },
      { code: '732', location: 'New Jersey', available: true },
      { code: '734', location: 'Michigan', available: true },
      { code: '737', location: 'Texas', available: true },
      { code: '740', location: 'Ohio', available: true },
      { code: '743', location: 'North Carolina', available: true },
      { code: '747', location: 'California', available: true },
      { code: '754', location: 'Florida', available: true },
      { code: '757', location: 'Virginia', available: true },
      { code: '760', location: 'California', available: true },
      { code: '762', location: 'Georgia', available: true },
      { code: '763', location: 'Minnesota', available: true },
      { code: '765', location: 'Indiana', available: true },
      { code: '769', location: 'Mississippi', available: true },
      { code: '770', location: 'Georgia', available: true },
      { code: '772', location: 'Florida', available: true },
      { code: '773', location: 'Illinois', available: true },
      { code: '774', location: 'Massachusetts', available: true },
      { code: '775', location: 'Nevada', available: true },
      { code: '779', location: 'Illinois', available: true },
      { code: '781', location: 'Massachusetts', available: true },
      { code: '785', location: 'Kansas', available: true },
      { code: '786', location: 'Florida', available: true },
      { code: '801', location: 'Utah', available: true },
      { code: '802', location: 'Vermont', available: true },
      { code: '803', location: 'South Carolina', available: true },
      { code: '804', location: 'Virginia', available: true },
      { code: '805', location: 'California', available: true },
      { code: '806', location: 'Texas', available: true },
      { code: '808', location: 'Hawaii', available: true },
      { code: '810', location: 'Michigan', available: true },
      { code: '812', location: 'Indiana', available: true },
      { code: '813', location: 'Florida', available: true },
      { code: '814', location: 'Pennsylvania', available: true },
      { code: '815', location: 'Illinois', available: true },
      { code: '816', location: 'Missouri', available: true },
      { code: '817', location: 'Texas', available: true },
      { code: '818', location: 'California', available: true },
      { code: '828', location: 'North Carolina', available: true },
      { code: '830', location: 'Texas', available: true },
      { code: '831', location: 'California', available: true },
      { code: '832', location: 'Texas', available: true },
      { code: '843', location: 'South Carolina', available: true },
      { code: '845', location: 'New York', available: true },
      { code: '847', location: 'Illinois', available: true },
      { code: '848', location: 'New Jersey', available: true },
      { code: '850', location: 'Florida', available: true },
      { code: '856', location: 'New Jersey', available: true },
      { code: '857', location: 'Massachusetts', available: true },
      { code: '858', location: 'California', available: true },
      { code: '859', location: 'Kentucky', available: true },
      { code: '860', location: 'Connecticut', available: true },
      { code: '862', location: 'New Jersey', available: true },
      { code: '863', location: 'Florida', available: true },
      { code: '864', location: 'South Carolina', available: true },
      { code: '865', location: 'Tennessee', available: true },
      { code: '870', location: 'Arkansas', available: true },
      { code: '872', location: 'Illinois', available: true },
      { code: '878', location: 'Pennsylvania', available: true },
      { code: '901', location: 'Tennessee', available: true },
      { code: '903', location: 'Texas', available: true },
      { code: '904', location: 'Florida', available: true },
      { code: '906', location: 'Michigan', available: true },
      { code: '907', location: 'Alaska', available: true },
      { code: '908', location: 'New Jersey', available: true },
      { code: '909', location: 'California', available: true },
      { code: '910', location: 'North Carolina', available: true },
      { code: '912', location: 'Georgia', available: true },
      { code: '913', location: 'Kansas', available: true },
      { code: '914', location: 'New York', available: true },
      { code: '915', location: 'Texas', available: true },
      { code: '916', location: 'California', available: true },
      { code: '917', location: 'New York', available: true },
      { code: '918', location: 'Oklahoma', available: true },
      { code: '919', location: 'North Carolina', available: true },
      { code: '920', location: 'Wisconsin', available: true },
      { code: '925', location: 'California', available: true },
      { code: '928', location: 'Arizona', available: true },
      { code: '929', location: 'New York', available: true },
      { code: '930', location: 'Indiana', available: true },
      { code: '931', location: 'Tennessee', available: true },
      { code: '934', location: 'New York', available: true },
      { code: '936', location: 'Texas', available: true },
      { code: '937', location: 'Ohio', available: true },
      { code: '938', location: 'Alabama', available: true },
      { code: '940', location: 'Texas', available: true },
      { code: '941', location: 'Florida', available: true },
      { code: '947', location: 'Michigan', available: true },
      { code: '949', location: 'California', available: true },
      { code: '951', location: 'California', available: true },
      { code: '952', location: 'Minnesota', available: true },
      { code: '954', location: 'Florida', available: true },
      { code: '956', location: 'Texas', available: true },
      { code: '959', location: 'Connecticut', available: true },
      { code: '970', location: 'Colorado', available: true },
      { code: '971', location: 'Oregon', available: true },
      { code: '972', location: 'Texas', available: true },
      { code: '973', location: 'New Jersey', available: true },
      { code: '978', location: 'Massachusetts', available: true },
      { code: '979', location: 'Texas', available: true },
      { code: '980', location: 'North Carolina', available: true },
      { code: '984', location: 'North Carolina', available: true },
      { code: '985', location: 'Louisiana', available: true },
      { code: '989', location: 'Michigan', available: true }
    ];

    // Shuffle and return a random selection of 20 area codes for better UX
    const shuffled = suggestedAreaCodes.sort(() => 0.5 - Math.random());
    const randomSelection = shuffled.slice(0, 20);

    return NextResponse.json({
      success: true,
      areaCodes: randomSelection,
      total: suggestedAreaCodes.length
    });

  } catch (error: any) {
    console.error('Get area codes API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch area codes' },
      { status: 500 }
    );
  }
}
